### ISSUE TITLE
Adding support for drain conflation queue

### ISSUE THREAD

**Issue by johnboy14** [tools4j/nobark#5]
I'm not sure if it's already supported, but I don't see any way to drain a merged conflation queue. What I want to do is stage data in the queue but at the end of a conflation interval e.g. 5 seconds, drain the queue and publish the data. The queue should be empty and ready for new additions. Am I missing something in the Java doc?

**Comment by terzerm** [comment]
Hi. Thanks for your interest in the library and for your question.

I am not sure I understand exactly what you want to do. Firstly, do you mean MergeConflationQueue?  (A MergeConflationQueue supports merging of old and new value if a value is enqueued and another one already exists in the queue with the same conflation key --- see javadoc).  Secondly, draining essentially just means polling the queue until it is empty, so you should be able to do that, you just have to make sure that nothing gets added concurrently in the meantime.

Now, conflation queues are normally used for producer/consumer situations (typically 2 or more threads, e.g. 1 producer thread and 1 consumer thread).  In trading applications we use conflation queues for instance for prices, where individual prices may not be so important, but you want to always have the newest price available (or, if you track lowest and highest price per day or interval, then you may want to use a merge conflation queue).  We would not use draining for prices.  We would typically only drain normal queues (non-conflating ones) e.g. when the application is shut down.  For instance, we would stop the producer (we no longer accept new executions into the queue), but we want to process all executions that we already have in the queue before shutting down the application.

Anyway, in your case, if you want to conflate 5 seconds, then drain, then conflate again, I would ask the following question:
- is it really important to drain the queue? because if it is important, then you need to stop or pause the producer while draining, which is not ideal.  
- as an option, you could also simply perform a drain-like operation every 5 seconds: you poll elements from the queue until you see a duplication conflation key coming out --- then you know you have removed all keys that were in the queue at the start of this operation (plus 1, the duplicated one).
- similar to the previous option, if you know how many conflation keys you have (e.g. n), and if you know that all of them are in the queue after 5 seconds, then simply poll n times and you can be sure you have polled exactly every key once

Options 2 and 3 are better because you do not need to stop the producer.

Hope this helps.

**Comment by johnboy14** [comment]
I obviously misunderstood the use case for the queue. My intention was to effectively snapshot incoming data in 5 second intervals and flush out any keys in the queue. The rate in which data is coming into the queue makes option 2 a non starter. I'll most likely just use a standard queue now and poll until the interval has passed and merge the data before publishing.
